@startuml
'https://plantuml.com/class-diagram

class App {
    + main()
    + start()
}


class ToDo {
    - description : String
    - stringDate : String
    - select : Checkbox
}

class ToDoListController {
    + changeItemCellEvent()
    + changeDescriptionCellEvent()
    + changeDateCellEvent()
    + addTaskClicked()
    + deleteTaskClicked()
    + viewCompleteTasksClicked()
    + viewRemainingClicked()
    + viewAllClicked()
    + clearAllClicked()
    + loadListClicked()
    + saveExternallyClicked()
}

ToDoListController *- App

ToDo *- ToDoListController


javafx.Application <|-- App


@enduml